version: 2

sources:
  - name: claims_lineage_source
    database: PRIZM_QA
    schema: DBT_RM

    tables:
      - name: CLAIM
        description: "Raw claims header table"

      - name: CLAIM_TX
        description: "Raw claim transactions table"